<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="10" failed="0" total="10" passed="0">
  <reporter-output>
    <line>
      <![CDATA[[INFO]: The test Browser is CHROME !!!]]>
    </line>
  </reporter-output>
  <suite name="NG-30181" duration-ms="2550" started-at="2015-11-03T12:35:31Z" finished-at="2015-11-03T12:35:34Z">
    <groups>
    </groups>
    <test name="Admin Login and search the isbn under master tab" duration-ms="2550" started-at="2015-11-03T12:35:31Z" finished-at="2015-11-03T12:35:34Z">
      <class name="com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity">
        <test-method status="FAIL" signature="start_test_session()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792]" name="start_test_session" is-config="true" duration-ms="0" started-at="2015-11-03T18:05:31Z" finished-at="2015-11-03T18:05:31Z">
          <exception class="org.openqa.selenium.remote.UnreachableBrowserException">
            <message>
              <![CDATA[Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'LNDA0021', ip: '10.161.236.51', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_51'
Driver info: driver.version: RemoteWebDriver]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'LNDA0021', ip: '10.161.236.51', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_51'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:242)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:155)
	at com.qait.mindtap.automation.WebDriverFactory.setRemoteDriver(WebDriverFactory.java:98)
	at com.qait.mindtap.automation.WebDriverFactory.getDriver(WebDriverFactory.java:67)
	at com.qait.mindtap.automation.TestSessionInitiator._configureBrowser(TestSessionInitiator.java:151)
	at com.qait.mindtap.automation.TestSessionInitiator.testInitiator(TestSessionInitiator.java:145)
	at com.qait.mindtap.automation.TestSessionInitiator.<init>(TestSessionInitiator.java:131)
	at com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity.start_test_session(TC01_Instructor_Adds_OR_Cancel_Topic_Activity.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:517)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:4444 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:143)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:89)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:134)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:578)
	... 36 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	... 49 more
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.remote.UnreachableBrowserException -->
          <reporter-output>
            <line>
              <![CDATA[[INFO]: The test Browser is CHROME !!!]]>
            </line>
          </reporter-output>
        </test-method> <!-- start_test_session -->
        <test-method status="SKIP" signature="Step_02_Instructor_Manages_Course_From_SSO()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792]" name="Step_02_Instructor_Manages_Course_From_SSO" duration-ms="0" started-at="2015-11-03T18:05:34Z" depends-on-methods="com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_01_Instructor_Logs_in_to_the_Application" finished-at="2015-11-03T18:05:34Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_02_Instructor_Manages_Course_From_SSO()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_02_Instructor_Manages_Course_From_SSO()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Step_02_Instructor_Manages_Course_From_SSO -->
        <test-method status="SKIP" signature="takeScreenshotonFailure(org.testng.ITestResult)[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792]" name="takeScreenshotonFailure" is-config="true" duration-ms="0" started-at="2015-11-03T18:05:34Z" finished-at="2015-11-03T18:05:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeScreenshotonFailure -->
        <test-method status="SKIP" signature="Step_09_Verify_Rolling_Week_UI()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792]" name="Step_09_Verify_Rolling_Week_UI" duration-ms="0" started-at="2015-11-03T18:05:34Z" depends-on-methods="com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_08_Instructor_Edit_Course_Details_To_Cancel" finished-at="2015-11-03T18:05:34Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_09_Verify_Rolling_Week_UI()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_09_Verify_Rolling_Week_UI()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Step_09_Verify_Rolling_Week_UI -->
        <test-method status="SKIP" signature="Step_08_Instructor_Edit_Course_Details_To_Cancel()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792]" name="Step_08_Instructor_Edit_Course_Details_To_Cancel" duration-ms="0" started-at="2015-11-03T18:05:34Z" depends-on-methods="com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_07_Verify_RollingWeekUI_And_Select_TopicView" finished-at="2015-11-03T18:05:34Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_08_Instructor_Edit_Course_Details_To_Cancel()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_08_Instructor_Edit_Course_Details_To_Cancel()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Step_08_Instructor_Edit_Course_Details_To_Cancel -->
        <test-method status="SKIP" signature="Step_10_Verify_Activity_Gets_Canceled()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792]" name="Step_10_Verify_Activity_Gets_Canceled" duration-ms="0" started-at="2015-11-03T18:05:34Z" depends-on-methods="com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_09_Verify_Rolling_Week_UI" finished-at="2015-11-03T18:05:34Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_10_Verify_Activity_Gets_Canceled()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_10_Verify_Activity_Gets_Canceled()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Step_10_Verify_Activity_Gets_Canceled -->
        <test-method status="PASS" signature="stop_test_session()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792]" name="stop_test_session" is-config="true" duration-ms="0" started-at="2015-11-03T18:05:34Z" finished-at="2015-11-03T18:05:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stop_test_session -->
        <test-method status="SKIP" signature="Step_04_Instructor_Edit_Course_Details_To_Add()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792]" name="Step_04_Instructor_Edit_Course_Details_To_Add" duration-ms="0" started-at="2015-11-03T18:05:34Z" depends-on-methods="com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_03_Verify_RollingWeekUI_And_Select_TopicView" finished-at="2015-11-03T18:05:34Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_04_Instructor_Edit_Course_Details_To_Add()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_04_Instructor_Edit_Course_Details_To_Add()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Step_04_Instructor_Edit_Course_Details_To_Add -->
        <test-method status="SKIP" signature="Step_06_Verify_Activity_Gets_Added()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792]" name="Step_06_Verify_Activity_Gets_Added" duration-ms="0" started-at="2015-11-03T18:05:34Z" depends-on-methods="com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_05_Verify_Rolling_Week_UI" finished-at="2015-11-03T18:05:34Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_06_Verify_Activity_Gets_Added()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_06_Verify_Activity_Gets_Added()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Step_06_Verify_Activity_Gets_Added -->
        <test-method status="SKIP" signature="Step_07_Verify_RollingWeekUI_And_Select_TopicView()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792]" name="Step_07_Verify_RollingWeekUI_And_Select_TopicView" duration-ms="0" started-at="2015-11-03T18:05:34Z" depends-on-methods="com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_06_Verify_Activity_Gets_Added" finished-at="2015-11-03T18:05:34Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_07_Verify_RollingWeekUI_And_Select_TopicView()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_07_Verify_RollingWeekUI_And_Select_TopicView()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Step_07_Verify_RollingWeekUI_And_Select_TopicView -->
        <test-method status="SKIP" signature="Step_03_Verify_RollingWeekUI_And_Select_TopicView()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792]" name="Step_03_Verify_RollingWeekUI_And_Select_TopicView" duration-ms="0" started-at="2015-11-03T18:05:34Z" depends-on-methods="com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_02_Instructor_Manages_Course_From_SSO" finished-at="2015-11-03T18:05:34Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_03_Verify_RollingWeekUI_And_Select_TopicView()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_03_Verify_RollingWeekUI_And_Select_TopicView()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Step_03_Verify_RollingWeekUI_And_Select_TopicView -->
        <test-method status="SKIP" signature="Step_01_Instructor_Logs_in_to_the_Application()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792]" name="Step_01_Instructor_Logs_in_to_the_Application" duration-ms="0" started-at="2015-11-03T18:05:34Z" finished-at="2015-11-03T18:05:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Step_01_Instructor_Logs_in_to_the_Application -->
        <test-method status="SKIP" signature="Step_05_Verify_Rolling_Week_UI()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792]" name="Step_05_Verify_Rolling_Week_UI" duration-ms="0" started-at="2015-11-03T18:05:34Z" depends-on-methods="com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_04_Instructor_Edit_Course_Details_To_Add" finished-at="2015-11-03T18:05:34Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_05_Verify_Rolling_Week_UI()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC01_Instructor_Adds_OR_Cancel_Topic_Activity.Step_05_Verify_Rolling_Week_UI()[pri:0, instance:com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity@16e8792] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Step_05_Verify_Rolling_Week_UI -->
      </class> <!-- com.qait.mindtap.tests.NG_30371.TC01_Instructor_Adds_OR_Cancel_Topic_Activity -->
    </test> <!-- Admin Login and search the isbn under master tab -->
  </suite> <!-- NG-30181 -->
</testng-results>
